name: ffmpeg
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      CFLAGS: -Os -no-pie -Wno-deprecated-declarations -Wno-implicit-function-declaration
      CXXFLAGS: -Os
      LDFLAGS: -all-static -framework Foundation -framework Cocoa -framework VideoToolbox
      PREFIX: /Users/runner/work/static-macos-executables/static-macos-executables/workspace
    steps:
      - run: git clone https://github.com/markus-perl/ffmpeg-build-script.git
      - run: cd ffmpeg-build-script && ./build-ffmpeg --build
      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: ffmpeg-build-script/workspace/bin/ffmpeg
